from ..constants import *

class Config(object):
    SECRET_KEY = APP_SECRET_KEY
    SQLALCHEMY_DATABASE_URI = DATABASE_URL
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    MAIL_SERVER = 'smtp.gmail.com'
    MAIL_PORT = 465
    MAIL_USE_TLS = False
    MAIL_USE_SSL = True
    MAIL_USERNAME = ICEBREAKER_EMAIL
    MAIL_PASSWORD = ICEBREAKER_MAIL_PASSWORD

