"""Add stock field to Chat model

Revision ID: 08939fe5245e
Revises: 529829646d3b
Create Date: 2025-03-05 12:34:47.438252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08939fe5245e'
down_revision = '529829646d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
