"""add email and password field to user

Revision ID: 4d3d394d5635
Revises: 23eff9caf39b
Create Date: 2025-03-20 21:21:08.554952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d3d394d5635'
down_revision = '23eff9caf39b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.alter_column('google_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('google_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
