"""modify stock_data table

Revision ID: 606da2540d2f
Revises: 0e66d4a35247
Create Date: 2025-03-05 22:32:01.654177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '606da2540d2f'
down_revision = '0e66d4a35247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.alter_column('stock_metadata',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_data', schema=None) as batch_op:
        batch_op.alter_column('stock_metadata',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=False)

    # ### end Alembic commands ###
