"""replace character with stock on chat table

Revision ID: e67ca2954c64
Revises: 606da2540d2f
Create Date: 2025-03-06 09:50:08.863395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e67ca2954c64'
down_revision = '606da2540d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.String(length=255), nullable=False))
        batch_op.drop_column('character_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
